# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


elasticsearch:
  host: elasticsearch
  port: 9200
  repository: cago-docker.rtp.openeng.netapp.com:5000
  image: %build_type%/elasticsearch
  tag : %build_tag%
  clusterName: ebs_elastic
  client:
    nodeMaster: false
    nodeIngest: true
    nodeData:  false
    httpEnable: true
    JavaOpts: -Xms4096m -Xmx4096m
    noOfMasters: 2
  data:
    nodeMaster: false
    nodeIngest: false
    nodeData:  true
    httpEnable: false
    JavaOpts: -Xms6144m -Xmx6144m
    noOfMasters: 2
  master:
    nodeMaster: true
    nodeIngest: false
    nodeData:  false
    httpEnable: false
    JavaOpts: -Xms768m -Xmx768m
    noOfMasters: 2

  networkHost: 0.0.0.0
  dataReplicas: 3 #minimum replicas for elasticsearch data.
  masterReplicas : 3
  clientReplicas : 3
  volumes:
    capacity: 500Gi

  resources:
    dataCPU: 3
    dataMemory: 12Gi
    masterCPU: 1
    masterMemory: 1.5Gi
    clientCPU: 1.25
    clientMemory: 8Gi

fluentd:
  host: fluentd-aggregator
  repository : cago-docker.rtp.openeng.netapp.com:5000
  replicas: 1 
  daemonset:
    image: %build_type%/fluentd_ds
    tag: %build_tag%
  aggr:
    image: %build_type%/fluentd_aggr
    tag: %build_tag%
  port: 24224
  resources:
      cpu: 2
      memory: 6Gi
  volumes:
    capacity: 100Gi

kibana:
  replicas : 1
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m

curator:
  repository: cago-docker.rtp.openeng.netapp.com:5000
  image: %build_type%/elastic_curator
  tag: %build_tag%

readinesscheck:
  repository: cago-docker.rtp.openeng.netapp.com:5000
  image: %build_type%/elastic_readinesscheck
  tag: %build_tag%

checkindices:
  repository: cago-docker.rtp.openeng.netapp.com:5000
  image: %build_type%/elastic_checkindices
  tag: %build_tag%

nodeAffinity:
  nodeAffinityEnabled: true
  instanceType: "m4.2xlarge"

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
