apiVersion: v1
kind: Service
metadata:
  name: {{.Values.elasticsearch.host}}
  namespace: {{ .Release.Namespace}}
  labels:
    component: elasticsearch
    role: client
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    nodePort: 30000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: {{ .Release.Namespace}}
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.fluentd.host}}
  namespace: {{ .Release.Namespace}}
  labels:
    component: fluentd-aggregator
spec:
  selector:
   k8s-app: fluentd-logging
  ports:
  - name: {{.Values.fluentd.host}}
    port: {{.Values.fluentd.port}}
    targetPort: {{.Values.fluentd.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: {{.Release.Namespace}}
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
    nodePort: 30001
  selector:
    k8s-app: kibana-logging
