apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-daemon
  namespace: {{.Release.Namespace}}
  labels:
    k8s-app: fluentd-ds-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-ds-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: fluentd
        image: {{.Values.fluentd.repository}}/{{.Values.fluentd.daemonset.image}}:{{.Values.fluentd.daemonset.tag}}
        imagePullPolicy: Always
        env:
        - name : FLUENT_UID
          value: "0"
        resources:
          limits:
            memory: 500Mi
            cpu: 400m
          requests:
            cpu: 400m
            memory: 500Mi
        volumeMounts:
        - name: fluentd-ds-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log/
        - name: varlibdocker
          mountPath: /var/lib/docker/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker/
      - name: fluentd-ds-config
        configMap:
          name: fluentd-ds-config
