# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


elasticsearch:
  host: elasticsearch
  port: 9200
  repository: <repo>:5000
  image: <elastic-search-image-name>
  tag : <tag-name>
  clusterName: ebs_elastic
  client:
    nodeMaster: false
    nodeIngest: true
    nodeData:  false
    httpEnable: true
    JavaOpts: -Xms1024m -Xmx1024m
    noOfMasters: 2
  data:
    nodeMaster: false
    nodeIngest: false
    nodeData:  true
    httpEnable: false
    JavaOpts: -Xms512m -Xmx512m
    noOfMasters: 2
  master:
    nodeMaster: true
    nodeIngest: false
    nodeData:  false
    httpEnable: false
    JavaOpts: -Xms512m -Xmx512m
    noOfMasters: 2

  networkHost: _site_,_lo_
  dataReplicas: 2  #minimum replicas for elasticsearch data.
  masterReplicas : 3
  clientReplicas : 2
  volumes:
    pvc: nfs-elastic-claim
    pv : nfs-elastic
    capacity: 50Gi   #capacity of the volume

  nfs:
    mountPath: /elastic
    server: 10.193.78.90

  resources:
    dataCPU: 1
    dataMemory: 2Gi
    masterCPU: 1
    masterMemory: 1Gi
    clientCPU: 1
    clientMemory: 2Gi

fluentd:
  host: fluentd-aggregator
  repository : <repository-addr (to fetch the fluentd image)>
  replicas: 1 
  daemonset:
    image: <fluentd  daemonset image-name>
    tag: <fluentd image tag>
  aggr:
    image: <fluentd aggregator image name>
    tag: <fluentd aggr tag name>
  port: 24224
  resources:
    cpu: 1
    memory: 2Gi

kibana:
  replicas : 1
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m

curator:
  repository: <repository-addr>
  image: <image-name>
  tag: <tag-name>

readinesscheck:
  repository: <repository-addr>
  image: <image-name>
  tag: <tag-name>

checkindices:
  repository: <repo-name>
  image: <image-name>
  tag: <tag-name>

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
