apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: registry.qstack.com  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd-read
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluentd-read
roleRef:
  kind: ClusterRole
  name: fluentd-read
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: {{ .Release.Namespace }}
