version: '3'

services:
  elasticsearch:
    image: ${DOCKER_REGISTRY}elasticsearch:${TAG-latest}
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - efk
  kibana:
    image: ${DOCKER_REGISTRY}kibana:${TAG-latest}
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch
  fluentbit:
    image: ${DOCKER_REGISTRY}fluentbit:${TAG-latest}
    ports:
      - "2020:2020"
      - "24224:24224"
    depends_on:
      - elasticsearch
    networks:
      - efk
networks:
  efk:
    driver: bridge
